### ISSUE TITLE
allTo works inconsistently

### ISSUE THREAD

**Issue by eddiemundo** [etorreborre/registry#7]
I noticed that the `argsTo` function is gone and its functionality is supposed to be subsumed by `allTo` but somehow whether expressions are inline or not affects it.
```
a :: Int -> Int -> IO Int 
a = undefined
b = outTo @RIO liftIO a
c = allTo @RIO b
d = allTo @RIO (outTo @RIO liftIO a)
```
![2020-08-17-151857_596x89_escrotum](https://user-images.githubusercontent.com/929157/90435514-20066a00-e09d-11ea-9379-e12fb230df61.png)
I expect `d` to be the same as `c` but it's not.

Also, as a side question, I've been doing the above using `argsTo` in the past to lift `IO` actions into `RIO` so I don't have to return `RIO` in my module creation functions unless necessary. Is that the right way of doing it?

**Comment by etorreborre** [comment]
That's interesting. I played with your example on the command line and it seems that the type inference gets in the way somehow. If I type:
```
d = allTo @RIO (outTo @RIO liftIO a :: Int -> Int -> RIO Int)
```
Then we get as expected:
```
d :: RIO Int -> RIO Int -> RIO Int
```
In order to avoid having to specify function types in extenso I've added back `argsTo`. My motivation for removing it was that `allTo` with a little tweak seemed to do the job and lift arguments to `m` even if the output was already in `m`. Which meant that I could get rid of `funAs` and keep only `valTo`/`funTo` to "lift" values and functions in the registry. Since this DSL for creating value graphs is already a bit unusual I thought it would be better to keep the API small. But GHC's type inference thinks otherwise :-).
